apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: healthy
      image: nginx
    - name: broken
      image: busybox
      command: ["exit", "1"]  # This will cause the pod to report failure
