apiVersion: v1
kind: Pod
metadata:
  name: probe-pod
spec:
  containers:
    - name: app
      image: nginx
      readinessProbe:
        httpGet:
          path: /invalid  # Invalid path causes probe to fail
          port: 80
        initialDelaySeconds: 2
        periodSeconds: 5
