apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: myapp  # Must match pod label
  ports:
    - protocol: TCP
      port: 80        # Service port
      targetPort: 80  # Container port
  type: ClusterIP     # Internal-only service
