apiVersion: batch/v1
kind: Job
metadata:
  name: fail-job
spec:
  template:
    spec:
      containers:
        - name: job
          image: busybox
          command: ["nope"]  # Invalid command
      restartPolicy: Never
